#pragma once

#include <stdint.h>

#define WIFI_LoRa_32_V3 true
#define USB_VID 0x303a
#define USB_PID 0x1001
#define I2C_HW_ADDR 0x3C

#define HELTEC_DISPLAY_HEIGHT 64
#define HELTEC_DISPLAY_WIDTH 128

#define HELTEC_TX GPIO_NUM_43
#define HELTEC_RX GPIO_NUM_44

#define HELTEC_SDA GPIO_NUM_41
#define HELTEC_SCL GPIO_NUM_42

#define HELTEC_SS GPIO_NUM_8
#define HELTEC_MOSI GPIO_NUM_10
#define HELTEC_MISO GPIO_NUM_11
#define HELTEC_SCK GPIO_NUM_9

#define HELTEC_A0 GPIO_NUM_1
#define HELTEC_A1 GPIO_NUM_2
#define HELTEC_A2 GPIO_NUM_3
#define HELTEC_A3 GPIO_NUM_4
#define HELTEC_A4 GPIO_NUM_5
#define HELTEC_A5 GPIO_NUM_6
#define HELTEC_A6 GPIO_NUM_7
#define HELTEC_A7 GPIO_NUM_8
#define HELTEC_A8 GPIO_NUM_9
#define HELTEC_A9 GPIO_NUM_10
#define HELTEC_A10 GPIO_NUM_11
#define HELTEC_A11 GPIO_NUM_12
#define HELTEC_A12 GPIO_NUM_13
#define HELTEC_A13 GPIO_NUM_14
#define HELTEC_A14 GPIO_NUM_15
#define HELTEC_A15 GPIO_NUM_16
#define HELTEC_A16 GPIO_NUM_17
#define HELTEC_A17 GPIO_NUM_18
#define HELTEC_A18 GPIO_NUM_19
#define HELTEC_A19 GPIO_NUM_20

#define HELTEC_T1 GPIO_NUM_1
#define HELTEC_T2 GPIO_NUM_2
#define HELTEC_T3 GPIO_NUM_3
#define HELTEC_T4 GPIO_NUM_4
#define HELTEC_T5 GPIO_NUM_5
#define HELTEC_T6 GPIO_NUM_6
#define HELTEC_T7 GPIO_NUM_7
#define HELTEC_T8 GPIO_NUM_8
#define HELTEC_T9 GPIO_NUM_9
#define HELTEC_T10 GPIO_NUM_10
#define HELTEC_T11 GPIO_NUM_11
#define HELTEC_T12 GPIO_NUM_12
#define HELTEC_T13 GPIO_NUM_13
#define HELTEC_T14 GPIO_NUM_14

#define HELTEC_VEXT GPIO_NUM_36
#define HELTEC_WHITE_LED GPIO_NUM_35
#define HELTEC_RST_OLED GPIO_NUM_21
#define HELTEC_SCL_OLED GPIO_NUM_18
#define HELTEC_SDA_OLED GPIO_NUM_17

#define HELTEC_RST_LORA GPIO_NUM_12
#define HELTEC_BUSY_LORA GPIO_NUM_13
#define HELTEC_DIO0 GPIO_NUM_14
